/* ============================================================
   Workability Lab — Daily Brief · EN editions database
   ------------------------------------------------------------
   HOW TO FEED THIS FILE (daily):
   Add a NEW edition object to the TOP of the EDITIONS array.
   Keep the newest edition first. Nothing else needs to change.
   Shape:
   {
     id:"2026-08-21", date:"2026-08-21", displayDate:"08/21/2026",
     weekday:"Friday", tag:"FRIDAY", edition:"08/21/2026",
     intro:"one-line intro...",
     sections:[ { heading:"Section", items:[ {headline,body,source,url} ] } ]
   }
   ============================================================ */

window.EDITIONS = [
  {
    id:"2026-08-21", date:"2026-08-21", displayDate:"08/21/2026",
    weekday:"Friday", tag:"FRIDAY", edition:"08/21/2026",
    cover:"https://www.yankodesign.com/images/design_news/2026/08/a-robot-dog-that-wants-you-to-go-outside-lassie-might/lassie-00-1050x788.jpg",
    intro:"Everything you need to start your day well informed. Today's edition spans AI business and geopolitics, a wave of products and studies on AI-made creation and authorship, new chapters in the automation-vs-jobs debate, and an environmental block on critical minerals, mobility and public space.",
    sections:[
      {heading:"AI: Business, Governance & Geopolitics",items:[
        {headline:"Brazil to build two AI supercomputers — one Chinese, one American",body:"The country is pursuing a dual strategy, with hardware from both Huawei and Nvidia — an attempt to keep a foot in each of the rival tech blocs instead of picking a side.",source:"The Next Web",url:"https://thenextweb.com/news/brazil-ai-supercomputers-huawei-nvidia-split"},
        {headline:"The US faces a 'capital crunch' as record debt collides with the AI spending spree",body:"On one side, the trillions Washington must borrow to pay for the past; on the other, the trillions the economy wants to invest in the AI future — a clash that could shape taxes, benefits and investment for generations.",source:"Axios",url:"https://www.axios.com/2026/08/21/national-debt-deficit-ai-spending"}
      ]},
      {heading:"AI: Creation, Products & Authorship",items:[
        {headline:"Adobe Firefly can now generate music, speech and sound effects",body:"Extending the tool to audio cements generative AI across the whole creative pipeline — image, video and now sound — with direct impact on scoring, dubbing and ad production.",source:"The Next Web",url:"https://thenextweb.com/news/adobe-firefly-audio-music-speech-sound-effects"},
        {headline:"Apple Music will label AI-made tracks later this year",body:"The feature expands the platform's Transparency Tags to flag AI-generated songs amid a flood of automated content on streaming services.",source:"Engadget",url:"https://www.engadget.com/2241260/apple-music-will-reportedly-label-any-ai-made-tracks-later-this-year/",image:"https://www.engadget.com/img/gallery/apple-music-will-reportedly-label-any-ai-made-tracks-later-this-year/intro-1787262611.jpg"},
        {headline:"Pew estimates 10% of the web already shows signs of AI authorship",body:"The study puts a concrete number on how machine-written text is spreading online, with implications for search, trust and the training of future models.",source:"The Next Web",url:"https://thenextweb.com/news/pew-ai-authorship-web-pages-study"},
        {headline:"A $100M startup wants to give companies 'AI employees'",body:"Anything AI 'employs' more than 150 colorful, cartoonish agents and argues humans could build software more easily by organizing work around AI characters.",source:"Fast Company",url:"https://www.fastcompany.com/91592566/exclusive-this-100-million-startup-wants-to-give-companies-ai-employees",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91592566-exclusive-this-100-million-startup-wants-to-give-companies-ai-employees.jpg"}
      ]},
      {heading:"AI, Work & Behavior",items:[
        {headline:"CEOs shift their messaging on AI and layoffs",body:"After months tying job cuts to AI-driven efficiency, executives are softening the narrative — a sign the link between automation and downsizing has become sensitive with staff and markets.",source:"Axios",url:"https://www.axios.com/2026/08/20/ceos-shift-messaging-around-ai-and-layoffs"},
        {headline:"Upwork's CEO insists the 'AI jobs apocalypse' isn't happening",body:"Hayden Brown says the data shows booming demand for AI skills, but also companies discovering that automation can't replace people so easily.",source:"Fast Company",url:"https://www.fastcompany.com/91592315/why-upworks-ceo-insists-the-ai-jobs-apocalypse-isnt-happening",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91592315-why-upworks-ceo-insists-the-ai-jobs-apocalypse-isnt-happening.jpg"},
        {headline:"OpenAI is losing female execs, and data shows women barely reach the top in AI",body:"A LinkedIn analysis across 27 countries finds women hold about 31% of AI leadership roles and under 13% of C-suite positions.",source:"Fast Company",url:"https://www.fastcompany.com/91591903/openai-is-losing-female-execs-but-data-shows-women-in-ai-dont-even-make-it-to-the-c-suite"},
        {headline:"Gen Z is skeptical of AI — and trusts its CEOs the least",body:"Asked about nine of the biggest names in AI, not a single leader topped 35% trust among young Americans.",source:"Fast Company",url:"https://www.fastcompany.com/91592384/gen-z-are-ai-skeptics-tech-ceo-they-trust-the-least-elon-musk-mark-zuckerberg-sam-altman",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91592384-young-people-hate-ai-ceos.jpg"},
        {headline:"Bank of America bars stacking work-from-home days",body:"The new policy stops hybrid staff from clustering their remote days, reviving the debate over why companies care which days — not how many — people work from home.",source:"Fast Company",url:"https://www.fastcompany.com/91592352/why-do-companies-care-which-days-you-work-from-home",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91592352-why-do-companies-care-which-days-you-work-from-home.jpg"}
      ]},
      {heading:"Privacy, Platforms & Child Safety",items:[
        {headline:"Senators press TikTok over a 'sinister' experiment that held back a safety feature",body:"The company reportedly delayed an algorithm safeguard during a test that involved a teen who later died by suicide, a case that exposes the tension between engagement and the safety of minors.",source:"Engadget",url:"https://www.engadget.com/2241153/senators-press-tiktok-on-sinister-experiment-held-back-algorithm-safety-feature/",image:"https://www.engadget.com/img/gallery/senators-press-tiktok-on-sinister-experiment-that-held-back-an-algorithm-safety-feature/intro-1787255215.jpg"},
        {headline:"Roblox pledges changes after an Australian regulator finds more child-safety lapses",body:"The regulator found the platform still lets adults contact children despite years of promises, adding to global pressure to protect minors in gaming environments.",source:"Engadget",url:"https://www.engadget.com/2240638/roblox-pledges-change-after-australia-finds-yet-more-child-safety-lapses/",image:"https://www.engadget.com/img/gallery/roblox-vows-to-make-changes-after-australian-regulator-found-yet-more-child-safety-lapses/intro-1787227165.jpg"},
        {headline:"OpenAI's Messages plugin summarizes who you talk to and about what",body:"The tool reads and digests iMessage conversations, raising questions about privacy and how far AI assistants should mediate personal communication.",source:"The Next Web",url:"https://thenextweb.com/news/chatgpt-imessage-plugin-apple-privacy"}
      ]},
      {heading:"Design, Product & Mobility",items:[
        {headline:"Lassie, the robot dog that wants to get you outside",body:"Inspired by how real dogs pull us out of bed, the concept uses robotic companionship to nudge walks and outdoor life — a turn toward wellbeing rather than productivity in home robotics.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/21/a-robot-dog-that-wants-you-to-go-outside-lassie-might/",image:"https://www.yankodesign.com/images/design_news/2026/08/a-robot-dog-that-wants-you-to-go-outside-lassie-might/lassie-00-1050x788.jpg"},
        {headline:"Heinz's new adjustable cap looks simple — the process wasn't",body:"The brand's first customizable ketchup bottle took real engineering to get the perfect pour, a reminder that everyday gestures still yield packaging innovation.",source:"Fast Company",url:"https://www.fastcompany.com/91591528/heinz-first-customizable-ketchup-bottle-has-an-adjustable-cap",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-91591528-heinz-adjustable-cap.jpg"},
        {headline:"Tesla's robotaxi fleet starts driving unsupervised in Austin",body:"After months of slow, safety-driver operation, the autonomous vehicles now appear to run fully driverless in the city — a milestone in the commercial rollout of self-driving.",source:"Engadget",url:"https://www.engadget.com/2240859/tesla-robotaxi-fleet-might-finally-be-driving-around-austin-unsupervised/",image:"https://www.engadget.com/img/gallery/teslas-robotaxi-fleet-might-finally-be-driving-around-austin-unsupervised/intro-1787240908.jpg"}
      ]},
      {heading:"Environment, Climate & Sustainability",items:[
        {headline:"Startup recovers copper from mines abandoned in the 1980s",body:"MIT spinout SiTration proposes extracting the metal from old open-pit mines to tackle a looming copper shortage — a case of urban mining for the energy transition.",source:"Fast Company",url:"https://www.fastcompany.com/91591887/mit-startup-recovers-copper-1980s-mines-shortage-looms",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-91591887-SiTration.jpg"},
        {headline:"Battery recycling becomes central to the US critical-minerals strategy",body:"The argument: recycling, not mining alone, is the path to American independence in strategic minerals — shifting the focus from extraction to the circular economy.",source:"Fast Company",url:"https://www.fastcompany.com/91591613/u-s-critical-mineral-strategy-depends-on-battery-recycling"},
        {headline:"Are underwater data centers actually sustainable for AI?",body:"The report weighs whether the ocean can become AI's next computing frontier without becoming its next environmental problem, as pushback pushes data centers off land.",source:"Fast Company",url:"https://www.fastcompany.com/91591381/underwater-data-centers-sustainable-ai-infrastructure",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91591381-are-underwater-data-centers-sustainable-for-ai-infrastructure.jpg"},
        {headline:"The Dutch build a ferry you power yourself with a crank",body:"The self-propelled crossing for cyclists reinforces the country's low-impact, active-mobility culture, turning the commute into a human gesture rather than a motorized one.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/20/the-dutch-just-built-a-ferry-you-power-yourself-with-a-crank/"},
        {headline:"Switzerland installs self-closing public benches that stay clean and dry",body:"Spotted in Lausanne, the spring-loaded seats fold up to stay dry and clean — urban furniture design aimed at comfort and upkeep of public space.",source:"Core77",url:"https://www.core77.com/posts/145128/In-Switzerland-Self-Closing-Public-Benches-that-Stay-Clean-and-Dry"}
      ]},
      {heading:"Society, Health & Longevity",items:[
        {headline:"The case for a ChatGPT for seniors",body:"If teens got guardrails, older users could benefit from extra protections too as AI becomes the new search bar — a take on aging and digital inclusion.",source:"Fast Company",url:"https://www.fastcompany.com/91592012/the-case-for-chatgpt-for-seniors",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91592012-why-we-need-a-chatgpt-for-boomers.jpg"},
        {headline:"A popular supplement could turn users into unwitting opioid addicts",body:"Kratom, sold in convenience stores and vape shops, is flagged as a highly addictive ingredient — a warning about loose supplement regulation and its health risks.",source:"Fast Company",url:"https://www.fastcompany.com/91591514/this-popular-supplement-could-turn-you-into-an-unwitting-opioid-addict",image:"https://images.fastcompany.com/image/upload/f_webp,c_fit,w_1280,q_auto/wp-cms-2/2026/08/p-1-91591514-this-popular-supplement-could-turn-you-into-an-unwitting-opioid-addict.jpg"},
        {headline:"'Stop calling childcare babysitting'",body:"The piece argues childcare is economic infrastructure, not a lesser service, repositioning the care economy as a base for productivity and the future of work.",source:"Fast Company",url:"https://www.fastcompany.com/91592129/stop-saying-childcare-is-babysitting"}
      ]}
    ]
  },

  {
    id:"2026-08-20", date:"2026-08-20", displayDate:"08/20/2026",
    weekday:"Thursday", tag:"THURSDAY", edition:"08/20/2026",
    cover:"https://www.yankodesign.com/images/design_news/2026/08/studzienno-27/studzienno_27_yanko_design_01.jpg",
    intro:"A scan of the last 24 hours. The day was marked by the geopolitical and political fight over AI infrastructure, an environmental block centered on air, water, energy and materials, and sociocultural signals on work, housing, health and behavior.",
    sections:[
      {heading:"AI: Business, Governance & Geopolitics",items:[
        {headline:"Anthropic preps supervoting shares for founders ahead of IPO",body:"The company is expected to create a class of shares with amplified voting power to keep Dario Amodei and the other founders in control despite small equity stakes — a governance design becoming common among AI giants on the eve of going public.",source:"The Next Web",url:"https://thenextweb.com/news/anthropic-supervoting-founders-ipo"},
        {headline:"China-led AI alliance keeps growing as Washington asks countries to pick a side",body:"WAICO now gathers 38 members around 'digital sovereignty', deepening the split of the world into rival tech blocs and pressuring countries to choose between the American and Chinese ecosystems.",source:"The Next Web",url:"https://thenextweb.com/news/china-digital-sovereignty-waico-38-members-pax-silica"},
        {headline:"China clears ByteDance and Tencent to import 10,000 H200 chips each",body:"The permission marks a partial reopening to Nvidia's top-end hardware and shows how chip access has become central currency in the AI race between the two largest economies.",source:"Engadget",url:"https://www.engadget.com/2239738/china-reportedly-allows-bytedance-tencent-import-10000-h200-chips/"},
        {headline:"Stripe says 'the singularity' has begun in payments",body:"The company reports that AI agents already move transactions autonomously via OpenRouter, signaling an economy in which software starts buying and selling without direct human intervention.",source:"Axios",url:"https://www.axios.com/2026/08/19/stripe-payments-openrouter-singularity"}
      ]},
      {heading:"AI, Work & Education",items:[
        {headline:"Google offers US college students a free year of AI Pro",body:"The package, which normally costs $200, joins the big-tech contest to lock in students early and normalize AI use in higher education.",source:"Engadget",url:"https://www.engadget.com/2240161/google-is-offering-college-students-a-year-of-ai-pro-for-free/",image:"https://www.engadget.com/img/gallery/google-is-offering-college-students-a-year-of-ai-pro-for-free/intro-1787159626.jpg"},
        {headline:"Why so many workers are turning down promotions",body:"Research suggests many professionals would rather forgo a bigger salary than take on the stress of climbing — a snapshot of shifting priorities and wellbeing at work.",source:"Fast Company",url:"https://www.fastcompany.com/91591451/why-so-many-workers-are-turning-down-promotions"},
        {headline:"How the 'mommy track' derails working women — and it's gotten worse",body:"The report shows mothers are still penalized in their careers, exposing how corporate structures remain ill-prepared for the care economy.",source:"Fast Company",url:"https://www.fastcompany.com/91592058/how-the-mommy-track-derails-working-women-and-its-only-gotten-worse"}
      ]},
      {heading:"AI, Surveillance & Health",items:[
        {headline:"Flock tests an AI tool that identifies people by their driving habits",body:"The system goes well beyond plate reading, building driver profiles from movement patterns — a leap in everyday surveillance with serious privacy implications.",source:"Engadget",url:"https://www.engadget.com/2240069/flock-testing-new-ai-police-tool-tracks-identifies-drivers/"},
        {headline:"FDA approves the first automated outpatient blood-draw device",body:"A robot could eventually perform the venous puncture in the clinic, an example of automating manual clinical tasks that reopens the debate over trust and the human role in care.",source:"Engadget",url:"https://www.engadget.com/2240357/a-robot-could-eventually-conduct-your-blood-draw-at-the-doctors-office/",image:"https://www.engadget.com/img/gallery/a-robot-could-eventually-conduct-your-blood-draw-at-the-doctors-office/intro-1787169711.jpg"},
        {headline:"mRNA cancer vaccine posts a positive Phase 3 result",body:"Moderna and Merck reported favorable data from an advanced trial, a milestone for personalized medicine and for the bet on mRNA platforms beyond antiviral vaccines.",source:"Fast Company",url:"https://www.fastcompany.com/91592278/moderna-stock-price-skyrocketing-today-mrna-cancer-vaccine-trial"}
      ]},
      {heading:"Design, Product & Architecture",items:[
        {headline:"A 'bent' desk that raises the monitor and keeps your hands low",body:"The concept breaks from the single flat surface and separates the screen and keyboard planes, tackling a chronic ergonomic problem of office and home work.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/19/someone-finally-bent-a-desk-to-put-your-monitor-higher-and-hands-low/"},
        {headline:"Being a senior designer no longer guarantees stability",body:"The article argues experienced professionals must question the very practices that got them to the top, in a field pressured by AI and restructuring.",source:"Fast Company",url:"https://www.fastcompany.com/91590774/being-a-senior-designer-doesnt-make-you-safe-anymore"},
        {headline:"Four wooden cabins trade Wi-Fi for wilderness",body:"The Studzienno 27 project bets on discreet architecture and disconnection as a wellbeing argument, aligned with the search for low-tech retreats and a slower life.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/19/four-tiny-wooden-cabins-that-trade-wi-fi-for-wilderness/",image:"https://www.yankodesign.com/images/design_news/2026/08/studzienno-27/studzienno_27_yanko_design_01.jpg"},
        {headline:"Unitree unveils a humanoid faster than Usain Bolt and goes public",body:"The world's largest humanoid-robot maker debuts in a record listing in China while showing impressive physical advances, a sign that general-purpose robotics is entering its commercial phase.",source:"Fast Company",url:"https://www.fastcompany.com/91592019/unitree-robotics-ipo-stock-price-trading-start-date-time-china-market-debut"}
      ]},
      {heading:"Environment, Climate & Sustainability",items:[
        {headline:"London's low-emission zone cleaned the air — and children's lungs grew",body:"After the ULEZ cut vehicle emissions, a five-year study found 'jaw-dropping' respiratory benefits in children, concrete evidence that urban environmental policy improves everyday health.",source:"Fast Company",url:"https://www.fastcompany.com/91591879/london-low-emissions-zone-cleaned-up-air-benefits-jaw-dropping-children-lung-health"},
        {headline:"Google uses AI to cut planes' condensation trails",body:"'Operation Blue Skies', with the UK government, tweaks flight routes to reduce contrails, which account for a meaningful part of aviation's climate impact — a low-cost, data-driven mitigation case.",source:"Engadget",url:"https://www.engadget.com/2240125/google-is-trying-to-solve-contrails-with-ai/"},
        {headline:"California's new tire standard is stricter than Europe's",body:"The rule targets the energy efficiency of replacement tires, an item that affects fuel use and emissions across millions of vehicles, putting the state ahead of Europe.",source:"The Next Web",url:"https://thenextweb.com/news/california-replacement-tire-efficiency-standard-europe"},
        {headline:"ADAC test reveals big energy losses in EV charging",body:"Among five models tested, one wasted roughly a quarter of the energy in home charging, data that helps consumers understand the real cost of EVs and the efficiency of the energy transition.",source:"The Next Web",url:"https://thenextweb.com/news/adac-ev-home-charging-losses-wallbox-socket"},
        {headline:"Denim has a water problem — and a digital dye wants to fix it",body:"Startup Wtrlss proposes a dyeing method that drastically cuts the water use of denim production, tackling one of fashion's most polluting and thirsty processes.",source:"Fast Company",url:"https://www.fastcompany.com/91591842/wtrlss-denim-has-a-water-problem-this-new-digital-dye-can-help"},
        {headline:"Foam-free packaging made from pressed rosemary waste",body:"Scentra replaces styrofoam with a biodegradable material repurposed from the herb industry — which still carries the aroma — an example of circular economy applied to consumer materials.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/19/this-foam-free-eco-packaging-is-made-from-compressed-rosemary-waste-and-it-carries-the-aroma-too/",image:"https://www.yankodesign.com/images/design_news/2026/08/auto-draft/scentra_rosemary_packaging_1-296x197.jpg"},
        {headline:"Backlash against data centers pushes AI infrastructure to space and the ocean",body:"With about 70% of Americans against having these complexes near home, companies start studying servers in orbit and at sea, a symptom of how environmental and social pressure is reshaping AI's expansion.",source:"Fast Company",url:"https://www.fastcompany.com/91590558/the-push-to-put-data-centers-anywhere-but-land"}
      ]},
      {heading:"Behavior, Society & Consumption",items:[
        {headline:"Traffic deaths rise 15% after major album releases",body:"A study links distracted driving to the debut of highly anticipated records, an unusual angle on how cultural habits and streaming affect everyday safety.",source:"Engadget",url:"https://www.engadget.com/2240233/study-finds-15-percent-increase-traffic-deaths-after-music-streaming-releases/",image:"https://www.engadget.com/img/gallery/study-finds-a-15-percent-increase-in-traffic-deaths-after-music-streaming-releases/intro-1787162348.jpg"},
        {headline:"Probiotic yogurt may slow aging, Japanese study says",body:"A daily serving, combined with a better diet and moderate exercise, reduced biological-age markers in older men — another sign of rising interest in longevity and preventive habits.",source:"Fast Company",url:"https://www.fastcompany.com/91584126/new-study-says-breakfast-staple-can-slow-down-how-fast-you-age"},
        {headline:"America's housing market is splitting in two",body:"Wealthier buyers stay active while unaffordability pushes out first-time buyers, deepening the generational inequality in access to housing.",source:"Fast Company",url:"https://www.fastcompany.com/91591964/americas-housing-market-is-splitting-in-two-and-one-group-of-buyers-is-getting-left-behind"}
      ]}
    ]
  },

  {
    id:"2026-08-19", date:"2026-08-19", displayDate:"08/19/2026",
    weekday:"Wednesday", tag:"WEDNESDAY", edition:"08/19/2026",
    cover:"https://media.thenextweb.com/2026/08/Governor-Josh-Shapiro.avif",
    intro:"The day was marked by an open divergence between the big labs on AI safety and by data centers becoming a political and environmental issue, a climate axis on extreme heat and new energy sources, and a sociocultural block on health, youth and the real impact of automation on jobs.",
    sections:[
      {heading:"AI: Safety, Governance & Politics",items:[
        {headline:"OpenAI blinks first in a safety standoff and pauses some model work",body:"The company suspended progress over safety concerns days after Anthropic reaffirmed that its own safeguards required no slowdown — the two largest labs now diverge publicly on how to manage risk on the eve of their IPOs.",source:"Axios",url:"https://www.axios.com/2026/08/19/openai-astra-safety-altman-anthropic"},
        {headline:"AI-generated bills are jamming the US Congress",body:"The House's legislative office is reportedly overwhelmed with error-filled AI-produced proposals, a symptom of how automating legal drafting can undermine the quality of public work.",source:"Engadget",url:"https://www.engadget.com/2238945/ai-generated-bills-causing-problems-in-the-capitol/"},
        {headline:"Republicans issue a stern warning to AI firms on data centers and elections",body:"An exclusive memo signals that AI infrastructure expansion has become a political risk, with the energy bill and local impact of data centers threatening to become an electoral liability.",source:"Axios",url:"https://www.axios.com/2026/08/19/gop-data-center-memo-ai-election"},
        {headline:"Pennsylvania becomes one of the hardest US states to build a data center in",body:"An executive order from Governor Josh Shapiro imposes new requirements on these complexes, an example of how states are starting to slow the AI infrastructure race in the name of energy, water and communities.",source:"The Next Web",url:"https://thenextweb.com/news/pennsylvania-shapiro-executive-order-ai-data-centres",image:"https://media.thenextweb.com/2026/08/Governor-Josh-Shapiro.avif"},
        {headline:"Turing Award winner calls the industry's bet on synthetic data a 'big mistake'",body:"Richard Sutton criticizes companies' strategy of offsetting the scarcity of real data by generating artificial data, defending learning from experience as a sounder path for AI.",source:"The Next Web",url:"https://thenextweb.com/news/richard-sutton-synthetic-data-big-mistake-experiential-learning"}
      ]},
      {heading:"AI, Work & Education",items:[
        {headline:"AI was supposed to threaten white-collar jobs, but another group is shrinking",body:"An economist shows several of the occupations flagged as vulnerable kept growing, while automation's real impact fell on jobs less discussed in the public debate.",source:"Fast Company",url:"https://www.fastcompany.com/91584114/ai-was-supposed-put-white-collar-professionals-risk-instead-another-group-shrinking-fast"},
        {headline:"Hochul launches an AI upskilling program focused on women",body:"The New York initiative tries to narrow the gender gap in the field, responding to the finding that new AI-linked roles were being filled mostly by men.",source:"Axios",url:"https://www.axios.com/2026/08/19/hochul-ai-workforce-women"},
        {headline:"Medly AI raises $8M to put an AI tutor in front of every UK exam student",body:"The round bets on personalized teaching for exams like the GCSE, at the center of the debate over how far AI should replace or extend teachers.",source:"The Next Web",url:"https://thenextweb.com/news/medly-ai-8m-seed-felix-capital-gcse-tutoring",image:"https://media.thenextweb.com/2026/08/Medly-AI-cofounders.avif"},
        {headline:"'Tokenmaxxing' is out; companies now chase value, not AI consumption",body:"After months rewarding heavy token use, companies like Tesla, Uber and Meta start capping spend and demanding concrete returns, a sign of maturing corporate AI adoption.",source:"Fast Company",url:"https://www.fastcompany.com/91590942/tokenmaxxing-is-out-valuemaxxing-is-in"}
      ]},
      {heading:"AI, Health & Daily Life",items:[
        {headline:"Doctors defend their role in the AI era",body:"Faced with the rise of automated diagnostic and triage tools, the US medical association seeks to delimit where human clinical judgment remains irreplaceable — a debate about trust, responsibility and care.",source:"Axios",url:"https://www.axios.com/2026/08/19/doctors-ai-health-care-ama"},
        {headline:"OpenAI starts rolling out a stricter 'teen mode' in ChatGPT",body:"The new version brings parental controls, study features and safety safeguards, with an attempt to auto-enroll young users — a milestone in designing AI products for minors.",source:"Engadget",url:"https://www.engadget.com/2238773/chatgpt-stricter-teen-mode-starts-rolling-out-today/"},
        {headline:"Mozilla brings AI to Firefox — but only if you want it",body:"The 'Smart Window' feature adds chat, search and browsing 'memories', with the option to keep AI fully off, a counterpoint to the compulsory integration adopted by rivals.",source:"Fast Company",url:"https://www.fastcompany.com/91590598/mozilla-is-bringing-ai-to-firefox-but-only-if-you-want-it"}
      ]},
      {heading:"Privacy, Platforms & Rights",items:[
        {headline:"Meta faces a $1.4 trillion trial over social-media addiction among children",body:"The suit brought by dozens of states, which could reach $1.4T in damages, accuses the company of violating minors' data protection and could redefine how Facebook and Instagram operate.",source:"Engadget",url:"https://www.engadget.com/2237547/meta-faces-a-1-4-trillion-reckoning-in-latest-trial-over-social-media-addiction/"},
        {headline:"Comcast's new system uses your home Wi-Fi to detect motion",body:"'Xfinity Shield' measures signal variations between router and devices to sense presence, merging physical and digital security — and raising questions about home surveillance and privacy.",source:"Engadget",url:"https://www.engadget.com/2239010/comcast-new-home-protection-setup-uses-wifi-to-detect-motion/"}
      ]},
      {heading:"Design, Product & Architecture",items:[
        {headline:"Why nobody has a fun couch anymore",body:"Ikea catalogs once flaunted colorful sofas until 'blanding' took over decor; the report analyzes how beige standardization erased boldness from home design.",source:"Fast Company",url:"https://www.fastcompany.com/91589209/why-no-one-has-a-fun-couch-anymore"},
        {headline:"A clock that lives on the edge of the table",body:"Industrial designer HoHyeon Lim's project rethinks a century-old object by balancing it on the edge of surfaces, an example of how formal constraint and provocation become a design argument.",source:"Core77",url:"https://www.core77.com/posts/145100/A-Clock-That-Lives-on-the-Edge"},
        {headline:"A Bulgarian agency designs a bank branch that looks like the inside of a crystal",body:"DA Architects' project turns walls into faceted, translucent surfaces, showing how service spaces seek sensory experience in a historically cold sector.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/18/this-bulgarian-bank-branch-looks-like-youre-sitting-inside-a-crystal/",image:"https://www.yankodesign.com/images/design_news/2026/08/auto-draft/dsk_bank_flagship_branch_5-296x197.jpg"},
        {headline:"Felice Varini's optical-illusion interiors",body:"The artist's interventions make rooms look as if they received a Photoshop layer, blurring the line between architecture, painting and spatial perception.",source:"Core77",url:"https://www.core77.com/posts/145098/Felice-Varinis-Optical-Illusion-Interiors"}
      ]},
      {heading:"Environment, Climate & Sustainability",items:[
        {headline:"Record El Niño may be a preview of Earth's future — and it isn't pretty",body:"Experts call the phenomenon a 'time machine' for offering a glimpse of the planet after crossing its climate tipping points, with extreme heat and cascading effects on daily life.",source:"Fast Company",url:"https://www.fastcompany.com/91591516/el-nino-2026-record-heat-time-machine-future-earth-climate"},
        {headline:"The extreme-heat problem for the power grid is changing",body:"With higher temperatures raising demand and stressing infrastructure, utilities begin to redesign grid operations, a climate-adaptation case reshaping energy planning.",source:"Axios",url:"https://www.axios.com/2026/08/19/extreme-heat-electric-grid-utilities-demand"},
        {headline:"A battery powered by algae",body:"Researchers are exploring a living alternative to traditional alkaline cells, pointing to a path of biological, biodegradable materials for energy storage.",source:"Fast Company",url:"https://www.fastcompany.com/91589823/this-battery-is-powered-by-algae"},
        {headline:"The $650 Fairphone 6+ is built to last eight years",body:"Against a smartphone replacement cycle of every three years, the repairable, modular device makes longevity and the right to repair a central argument for sustainable consumption.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/19/most-phones-last-3-years-this-650-fairphone-6-is-built-for-8/",image:"https://www.yankodesign.com/images/design_news/2026/08/most-phones-last-3-years-this-650-fairphone-6-is-built-for-8/fairphone-gen-6-plus-06-296x197.jpg"},
        {headline:"Off-grid modular home designed from a farm-equipment catalog",body:"The concept seeks affordable, sustainable housing by repurposing existing industrial components instead of new materials and supply chains, a take on circular economy applied to housing.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/18/someone-designed-an-off-grid-modular-home-from-a-farm-equipment-catalog/"},
        {headline:"Your dead computer's CD-ROM drive can become an audio player",body:"The upcycling project gives new life to discarded electronics, drawing attention to the tech waste piling up in drawers and to the value of creative reuse.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/18/your-dead-computers-cd-rom-drive-can-become-a-real-audio-player-thanks-to-this-upcycled-project/",image:"https://www.yankodesign.com/images/design_news/2026/08/642215/cd_rom_player_01_1-296x197.jpeg"}
      ]}
    ]
  },

  {
    id:"2026-08-18", date:"2026-08-18", displayDate:"08/18/2026",
    weekday:"Tuesday", tag:"TUESDAY", edition:"08/18/2026",
    cover:"https://media.thenextweb.com/2026/08/productivity-crisis-digital-transformation-kboodl.avif",
    intro:"Threads for the day: AI's financial heat ahead of IPOs and the build-out of its infrastructure, a privacy-and-rights angle on data used to train models, an environmental axis on wildfire smoke and climate adaptation, and a sociocultural block on unequal AI access, health and housing.",
    sections:[
      {heading:"AI: Business, Governance & Infrastructure",items:[
        {headline:"Anthropic's revenue tops $65B on an annualized basis ahead of its IPO",body:"The jump in run rate underscores the race between Anthropic and OpenAI toward going public and fuels the debate over whether financial fundamentals keep pace with the sector's valuations.",source:"Axios",url:"https://www.axios.com/2026/08/17/anthropic-revenue-run-rate-ipo-openai"},
        {headline:"Groq raises $350M Series A at $3.5B, with Nvidia joining the round",body:"The investment in the inference-chip maker shows the fight for AI hardware alternatives and Nvidia's strategy of funding key pieces of its own ecosystem.",source:"The Next Web",url:"https://thenextweb.com/news/groq-3-5bn-valuation-funding-round",image:"https://media.thenextweb.com/2026/08/Groq-logo.avif"},
        {headline:"SEC staff accepts that data-center securitization falls outside Dodd-Frank risk retention",body:"The opinion, tied to a $500B plan, treats data centers as collateral and opens the way to finance AI infrastructure like a real-estate asset, widening scrutiny of circular deals.",source:"The Next Web",url:"https://thenextweb.com/news/sec-data-centre-securitisation-nvidia-500bn-dodd-frank"},
        {headline:"OpenAI denies it disbanded its 'preparedness' team in a restructuring",body:"After reports that the group assessing catastrophic model risks had been dismantled, the company says it merely reorganized roles — an episode that reignites the debate over safety governance amid rapid expansion.",source:"Engadget",url:"https://www.engadget.com/2237916/openai-reportedly-disbanded-its-preparedness-team-as-part-of-streamlining-process/"},
        {headline:"Target names its first chief AI officer as retail ramps up investment",body:"The role, which barely existed two years ago, now appears in three of every four large organizations, a sign that AI is becoming a structured executive function inside companies.",source:"The Next Web",url:"https://thenextweb.com/news/target-first-chief-ai-officer-chandhu-nair",image:"https://media.thenextweb.com/2026/08/target-first-chief-ai-officer-chandhu-nair.avif"}
      ]},
      {heading:"AI, Privacy & Security",items:[
        {headline:"Cursor turns on 'Origin' by default for paid users without publishing data terms",body:"The coding tool started running with no clear opt-out and no detail on who controls the code sent, an alert about transparency in programming assistants.",source:"The Next Web",url:"https://thenextweb.com/news/cursor-origin-opt-out-data-terms-spacex-github-outage"},
        {headline:"Google picked and paid the firm that anonymized Spirit Airlines' data",body:"In the airline's bankruptcy auction, the big tech funded the firm handling passenger data, raising questions about conflict of interest and the fate of personal information in insolvency proceedings.",source:"The Next Web",url:"https://thenextweb.com/news/google-spirit-airlines-data-10m-bankruptcy-auction-mercor"},
        {headline:"An AI agent built a working macOS exploit in four hours",body:"The case shows how autonomous models accelerate both cyber defense and attack, compressing the time between discovering a vulnerability and exploiting it.",source:"The Next Web",url:"https://thenextweb.com/news/macos-screen-sharing-flaw-cve-2026-65400-monero-miner"},
        {headline:"Apple forced to stop favoring its own apps in data-collection prompts",body:"A German competition authority ruled that the company's permission pop-ups favored its services over rivals, a relevant precedent for consent design and platform regulation.",source:"Engadget",url:"https://www.engadget.com/2238496/apple-is-forced-to-stop-favoring-its-own-apps-in-personal-data-collection-prompts/"}
      ]},
      {heading:"AI, Culture & Rights",items:[
        {headline:"AI companies are buying used books by the thousands — and some may be destroyed in training",body:"Mass orders to scan legally acquired works gave unexpected life to used-book shops, but expose the tension between copyright and models' hunger for data.",source:"Fast Company",url:"https://www.fastcompany.com/91591196/ai-companies-buying-used-books-by-thousands"},
        {headline:"ByteDance agrees to rein in its AI models to protect Hollywood IP",body:"TikTok's owner struck a deal with the Motion Picture Association to limit the generation of content replicating protected characters and works, a landmark in the fight between generative AI and the creative industry.",source:"Engadget",url:"https://www.engadget.com/2238384/bytedance-agrees-to-reel-in-its-ai-models-to-protect-hollywood-ip/"},
        {headline:"Fear of AI is fueling the 'handmade' branding trend",body:"Companies begin emphasizing human, artisanal work in their identities to differentiate from automated production, a branding move that turns authenticity into market value.",source:"Fast Company",url:"https://www.fastcompany.com/91584397/ai-fears-are-fueling-the-handmade-branding-trend-technology-ai-fear-handmade-design"}
      ]},
      {heading:"Future of Work",items:[
        {headline:"Women are being left out of the AI jobs boom",body:"Data show new AI-linked roles are being filled mostly by men, widening a gender gap precisely in the field expected to concentrate opportunities over the next decade.",source:"Axios",url:"https://www.axios.com/2026/08/18/ai-women-jobs-hiring"},
        {headline:"Your AI is emailing the other person's AI — and nobody's in charge",body:"With half of US workers using AI to draft messages, concern grows over unsupervised communication and the need for new accountability rules at work.",source:"Fast Company",url:"https://www.fastcompany.com/91588570/ai-emailing-ai-nobodys-in-charge"},
        {headline:"The productivity crisis hidden inside America's digital transformation",body:"The report argues that massive tech investment hasn't translated into productivity gains, suggesting that the rushed adoption of tools may be creating more friction than efficiency.",source:"The Next Web",url:"https://thenextweb.com/news/productivity-crisis-digital-transformation-kboodl",image:"https://media.thenextweb.com/2026/08/productivity-crisis-digital-transformation-kboodl.avif"}
      ]},
      {heading:"Design, Product & Architecture",items:[
        {headline:"Sigma's minimalist BF camera by Iwasaki Design Studio",body:"The body machined from a single block of aluminum takes Japanese minimalism to the limit, an example of how formal restraint and materiality become a design argument in consumer products.",source:"Core77",url:"https://www.core77.com/posts/145087/Sigmas-Minimalist-BF-Camera"},
        {headline:"Leitz's portable desk organizer built for hot-desking",body:"The object answers the reality of offices with no fixed seats, where workers carry their own kit — design that materializes the new routines of hybrid work.",source:"Core77",url:"https://www.core77.com/posts/145074/The-Leitz-Portable-Desk-Organizer-for-Hot-Desking"},
        {headline:"The Redmi K100 Pro turns its glass back into a glowing sketchpad",body:"Using photoluminescent material as an interface feature shows how makers seek sensory, playful differentiation in an increasingly homogeneous smartphone market.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/17/the-redmi-k100-pro-turns-its-glass-back-into-a-glowing-sketchpad/"},
        {headline:"A 6-meter minimal home built for nomads who refuse to compromise on comfort",body:"The project reacts to the trend of ever-larger 'tiny homes' and revives the original appeal of mobility and autonomy, a take on new ways of living.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/17/this-20-foot-tiny-home-by-is-built-for-nomads-who-refuse-to-compromise/"}
      ]},
      {heading:"Environment, Climate & Sustainability",items:[
        {headline:"Watch Duty expands beyond wildfires as disasters intensify",body:"The nonprofit app that became a reference for wildfire alerts starts monitoring floods nationwide, an example of civic climate-adaptation infrastructure built by volunteers.",source:"Fast Company",url:"https://www.fastcompany.com/91590856/watch-duty-is-expanding-beyond-wildfires-as-disasters-grow-more-extreme"},
        {headline:"NASA map reveals the Northern Hemisphere's summer of wildfire smoke",body:"The visualization shows how pollution from hundreds of fires in Canada and the US Northwest travels thousands of kilometers, making the cross-border reach of the climate crisis visible.",source:"Fast Company",url:"https://www.fastcompany.com/91589686/this-stunning-nasa-map-tracks-our-summer-of-wildfire-smoke"},
        {headline:"In Holland, a self-powered river crossing for cyclists",body:"The low-tech solution replaces motorized ferries with a system driven by the current itself, a case of sustainable mobility design that needs no energy or emissions.",source:"Core77",url:"https://www.core77.com/posts/145086/In-Holland-a-Self-Powered-River-Crossing-for-Bikes"},
        {headline:"A Georgia show turns 9 broken 3D prints into music",body:"The exhibition gives creative purpose to the waste piling up in digital-fabrication labs, drawing attention to prototyping's quiet waste and to circular economy in design.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/17/the-georgia-art-show-turning-9-broken-3d-prints-into-music/"}
      ]},
      {heading:"Sociocultural & Behavior",items:[
        {headline:"Kindergarten vaccine exemptions rise again in the US",body:"The CDC reports vaccination rates fell in the 2025–2026 school year and exemptions grew in 41 states, a sign of eroding trust in immunization with public-health implications.",source:"Axios",url:"https://www.axios.com/2026/08/17/kindergarten-vaccine-rates-fall"},
        {headline:"FBI logs the largest violent-crime drop in 90 years in 2025",body:"The data contradict public perceptions of insecurity and reopen the debate over safety policy, campaign narratives and the gap between statistics and fear.",source:"Axios",url:"https://www.axios.com/2026/08/18/fbi-violent-crime-drop-2025"},
        {headline:"First-time homebuyers could use 529 accounts for a down payment",body:"A legislative proposal would allow up to $35,000 of education savings to go toward a first home, reshaping the relationship between funding studies and access to housing for younger people.",source:"Fast Company",url:"https://www.fastcompany.com/91590616/first-time-homebuyers-could-soon-get-a-new-way-to-find-35000-for-a-down-payment"}
      ]}
    ]
  },

  {
    id:"2026-08-17", date:"2026-08-17", displayDate:"08/17/2026",
    weekday:"Monday", tag:"MONDAY", edition:"08/17/2026",
    intro:"The week opens with an AI reality check — from admissions that the promises fell short to the geopolitical scramble for allies — an environmental axis on how drought and fire already reshape energy, food and finance, and a sociocultural read on loneliness, new jobs and the human cost of automation.",
    sections:[
      {heading:"AI: Governance, Frontiers & Business",items:[
        {headline:"Dario Amodei admits AI companies haven't delivered what they promised",body:"The Anthropic CEO acknowledges the gap between the 'cure cancer' rhetoric and concrete results, at a moment when the sector is heading for IPOs and needs to rebuild public trust.",source:"The Next Web",url:"https://thenextweb.com/news/dario-amodei-ai-public-trust-cure-cancer-ipo"},
        {headline:"A new ChatGPT feature logs your keystrokes and stores everything in plain text",body:"The function that gives the desktop assistant memory stores history without encryption, exposing a privacy flaw in products that now watch every keystroke.",source:"The Next Web",url:"https://thenextweb.com/news/openai-chatgpt-computer-history-mac-keystrokes"},
        {headline:"Anthropic ran 133 million conversations with bioweapon filters off",body:"The company's risk report reveals a gap between safety classifiers and human feedback, reigniting the debate over governing dual-use risks at scale.",source:"The Next Web",url:"https://thenextweb.com/news/anthropic-risk-report-bio-classifiers-human-feedback-gap"},
        {headline:"US to ask 35 countries to choose between Washington and Beijing on AI",body:"The 'Pax Silica' initiative tries to form a Western coalition of infrastructure and models, turning the tech race into a test of geopolitical alignment.",source:"The Next Web",url:"https://thenextweb.com/news/pax-silica-us-letter-35-countries-china-ai-coalition"},
        {headline:"Nvidia halved its $250B pledge to OpenAI — and revealed what it owns",body:"The pullback, disclosed alongside filings showing stakes in SpaceX and Intel, signals financial caution at the heart of the AI boom and more scrutiny of circular deals between makers and customers.",source:"The Next Web",url:"https://thenextweb.com/news/nvidia-openai-backstop-halved-13f-spacex-intel"},
        {headline:"What happens to the secrets you tell AI",body:"The report investigates how OpenAI, Meta, Google and Anthropic handle intimate data shared in chats, a warning about what stays stored when the assistant becomes a confidant.",source:"Axios",url:"https://www.axios.com/2026/08/17/secrets-share-ai-openai-meta-google-anthropic"}
      ]},
      {heading:"AI & Future of Work",items:[
        {headline:"An AI manager fires its first human worker — after forgetting its own rules",body:"At a San Francisco store, the autonomous system dismissed a worker for absences, but only after being reminded of the attendance policy it had written itself, a tragicomic portrait of the limits of automated management.",source:"The Next Web",url:"https://thenextweb.com/news/andon-market-luna-ai-store-manager-fires-employee"},
        {headline:"The surprising reason AI layoffs hurt productivity",body:"A study indicates cuts attributed to automation overload those who remain and erode teams' tacit knowledge, suggesting the efficiency promise can backfire.",source:"Fast Company",url:"https://www.fastcompany.com/91589194/surprising-reason-ai-layoffs-hurt-worker-productivity"},
        {headline:"Sam Altman says four years of college may be more than the world needs",body:"The OpenAI chief questions the length of higher education amid the automation of entry-level roles, heating up the debate over training, internships and the future of early careers.",source:"The Next Web",url:"https://thenextweb.com/news/sam-altman-college-too-long-interns-entry-level"},
        {headline:"'Holiday hoarding' becomes a silent workplace crisis",body:"The report shows how the habit of banking days off instead of resting fuels burnout, a symptom of the insecurity marking today's world of work.",source:"Fast Company",url:"https://www.fastcompany.com/91589261/holiday-hoarding-is-a-workplace-crisis"}
      ]},
      {heading:"Design, Product & Architecture",items:[
        {headline:"A cleaning robot that knows exactly when a bathroom needs it",body:"Instead of fixed rounds twice a day, the system uses sensors to act on demand, an example of how data and robotics rethink a space historically ignored by design.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/16/the-cleaning-robot-that-knows-when-a-bathroom-needs-it/"},
        {headline:"On the Athens Riviera, sculptural balconies become an extension of home life",body:"The project turns the balcony into a space of shade, conversation and sea air, showing how Mediterranean architecture designs daily life around light and coastal climate.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/16/where-sculptural-balconies-meet-mediterranean-light-and-coastal-living/"},
        {headline:"Jif's new logo is a lesson in rebranding through restraint",body:"The peanut-butter brand shows that the best visual refresh often lies in what you preserve, not what you reinvent — a counterpoint to the appetite for radical redesigns.",source:"Fast Company",url:"https://www.fastcompany.com/91590609/jifs-new-logo-is-a-rebrand-done-right"},
        {headline:"Tesla promises a flying car; BYD already has one that makes more sense",body:"While Musk announces yet another uncertain prototype, the Chinese rival already delivers a vehicle with an aerial module, illustrating the shift of cutting-edge automotive design to China.",source:"Fast Company",url:"https://www.fastcompany.com/91590567/tesla-says-a-flying-car-is-coming-byd-already-has-one-that-makes-sense"},
        {headline:"LG's humanoid robot arrives in 2027 running Nvidia's Isaac GR00T platform",body:"The partnership puts the Korean maker in the race for general-purpose robots, a sign that humanoid robotics is leaving the lab for commercial products.",source:"The Next Web",url:"https://thenextweb.com/news/lg-nvidia-humanoid-robot-2027-isaac-groot"}
      ]},
      {heading:"Environment, Climate & Energy",items:[
        {headline:"Wildfires become a power-grid planning problem",body:"Utilities begin designing infrastructure around fire risk, an example of how climate adaptation already reshapes basic engineering and energy decisions.",source:"Axios",url:"https://www.axios.com/2026/08/17/wildfires-electric-grid-planning-energy-infrastructure"},
        {headline:"Heat has become a banking-collateral crisis — in Italy's cheese",body:"With the climate affecting the aging and value of Parmesan stocks used as loan collateral, the report shows how warming seeps even into financial balance sheets.",source:"Axios",url:"https://www.axios.com/2026/08/16/italy-cheese-heat-banks"},
        {headline:"Tyson closes beef plants as drought worsens the US cattle shortage",body:"The food giant acts on the climate risks it had been flagging to investors, highlighting the impact of extreme weather on the protein chain and consumer prices.",source:"Fast Company",url:"https://www.fastcompany.com/91590481/tyson-foods-beef-plant-closures-extreme-drought-cattle-shortage"},
        {headline:"EV prices rise for the first time in 2026 — because of discounts",body:"Shrinking incentives and supply problems made EVs more expensive in the US, exposing the fragility of the energy transition when subsidies retreat.",source:"The Next Web",url:"https://thenextweb.com/news/us-ev-prices-rising-july-2026-incentives-supply"},
        {headline:"Weber will switch off the June oven's AI camera — and a $90 air fryer does the same",body:"The 'smart' feature of a $999 oven will be discontinued remotely, a case that exposes the planned obsolescence and waste built into connected appliances.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/16/weber-is-shutting-off-the-june-ovens-ai-camera-and-a-90-air-fryer-already-does-the-same-thing/"}
      ]},
      {heading:"Sociocultural & Behavior",items:[
        {headline:"The meetup boom tries to cure Gen Z loneliness",body:"App-organized in-person gatherings are growing as a response to isolation and the fatigue of digital relationships, a symptom of how young people seek to rebuild bonds off-screen.",source:"Axios",url:"https://www.axios.com/2026/08/17/meetup-dating-gen-z-loneliness"},
        {headline:"E-bike injuries surge among US kids",body:"Amid rising accidents, some jurisdictions want to hold parents of young riders liable, a debate over safety, mobility and the limits of children's use of motorized vehicles.",source:"Fast Company",url:"https://www.fastcompany.com/91590436/e-bike-injuries-kids-surging-u-s-these-jurisdictions-want-parents-liable"},
        {headline:"A US university launches a content-creation major — critics question the 'influencer degree'",body:"Arizona State's course formalizes as a profession what was once a hobby, sparking a discussion about the educational value and economy behind creator culture.",source:"Fast Company",url:"https://www.fastcompany.com/91590429/u-s-university-just-launched-major-content-creation-critics-question-influencer-degree"},
        {headline:"Tired of being ghosted by recruiters, a designer starts sending 'unhinged' résumés",body:"Felix Toohey's viral 'Ghosting Busters' series turns hiring-process frustration into a good-humored critique of recruitment practices and corporate silence.",source:"Fast Company",url:"https://www.fastcompany.com/91590737/designer-jobs-ghosted-employers-sending-unhinged-resumes"},
        {headline:"Why prescription drug prices are falling",body:"The report analyzes the notable drop in US drug prices, with direct effects on access to care, family budgets and the pharmaceutical market.",source:"Axios",url:"https://www.axios.com/2026/08/17/drug-prices-medicare-trump"}
      ]}
    ]
  },

  {
    id:"2026-08-14", date:"2026-08-14", displayDate:"08/14/2026",
    weekday:"Friday", tag:"FRIDAY", edition:"08/14/2026",
    cover:"https://media.thenextweb.com/2026/08/New-York-Salesforce-Tower.avif",
    intro:"Threads for the day: AI's financial and regulatory maturation — from pre-IPO reshuffles to markets for compute — an environmental axis on the collision of energy, water and digital infrastructure, and a sociocultural read on precarious work, demographic change and surveillance.",
    sections:[
      {heading:"AI: Investment, Governance & Frontiers",items:[
        {headline:"OpenAI loses senior execs in a pre-IPO cleanup",body:"The company is going through a round of top-level departures as it prepares to go public, a sign of how the IPO race reorganizes leadership and priorities at the sector's core.",source:"Axios",url:"https://www.axios.com/2026/08/14/openai-executive-greg-brockman-ipo"},
        {headline:"Open-source AI comes under US government scrutiny",body:"Open-weight models now face more regulatory scrutiny, in a debate that pits transparency and innovation against national-security concerns.",source:"Axios",url:"https://www.axios.com/2026/08/14/open-source-ai-government-scrutiny"},
        {headline:"AI compute becomes a tradable commodity starting October 5",body:"A new GPU-futures market will make the price of processing power public, turning AI capacity into a financial asset trackable like oil or grain.",source:"The Next Web",url:"https://thenextweb.com/news/cme-silicon-data-gpu-compute-futures-october-5"},
        {headline:"Massive AI spending still hasn't shown up in a key economic metric",body:"Despite the billions invested, broader productive capital investment remains timid, suggesting the boom hasn't yet translated into widespread gains.",source:"Axios",url:"https://www.axios.com/2026/08/14/ai-spending-tech-capital"},
        {headline:"Josh Kushner raises $2B to buy the companies AI aims to replace",body:"Instead of selling software, Thrive Holdings acquires entire businesses exposed to automation, a bet that value will migrate to whoever controls operations, not just the models.",source:"The Next Web",url:"https://thenextweb.com/news/thrive-holdings-2bn-12bn-valuation-softbank-ai-rollup"},
        {headline:"Chatbots reject election theories but generate fake images on demand",body:"A study shows the big assistants refuse to endorse election lies in text while their image tools produce fabricated 'proof' of those same claims — a dangerous moderation gap.",source:"Fast Company",url:"https://www.fastcompany.com/91589221/chatbots-argue-against-election-conspiracy-theories-then-willingly-illustrate-them"},
        {headline:"A convergence of biological risks worries experts",body:"The combination of AI applied to biology with frontier lab research raises the chance of biological threats, a warning about dual-use governance.",source:"Axios",url:"https://www.axios.com/2026/08/14/biological-threats-ai-lab-research"}
      ]},
      {heading:"AI & Future of Work",items:[
        {headline:"US employers increasingly rely on 'disposable' workers",body:"A labor economist explains the rise of three kinds of precarious arrangements, a portrait of a more fragmented, insecure workforce under cost and automation pressure.",source:"Fast Company",url:"https://www.fastcompany.com/91588548/u-s-employers-relying-more-more-disposable-workers-heres-why"},
        {headline:"Salesforce cuts another 133 jobs — and the filings don't mention AI",body:"The new round of layoffs at the software giant avoids attributing cuts to automation, showing how companies manage the narrative of AI's impact on jobs.",source:"The Next Web",url:"https://thenextweb.com/news/salesforce-133-layoffs-washington-california-ai-restructuring",image:"https://media.thenextweb.com/2026/08/New-York-Salesforce-Tower.avif"}
      ]},
      {heading:"Design, Product & Architecture",items:[
        {headline:"Beni is the $549 camera robot that films by itself while you live",body:"The bipedal device needs no operator and proposes to replace an entire camera crew, an example of how robotics and AI redesign the very idea of capturing images.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/13/beni-is-what-sony-aibo-grew-up-to-be-a-549-camera-robot-that-captures-life-while-you-live-it/"},
        {headline:"A school security system uses light to show escape routes during shootings and disasters",body:"The building itself indicates the safest path in emergencies, a case of design that turns architecture into a wayfinding tool under stress.",source:"Fast Company",url:"https://www.fastcompany.com/91589192/this-school-security-system-displays-safe-evacuation-routes-during-shootings-and-disasters"},
        {headline:"Haüsa Homes shows how to fold a whole house into a shipping container",body:"The Argentine studio bets on flatpack homes that fit in sea freight, a path to fast, modular housing with a smaller logistics footprint.",source:"Core77",url:"https://www.core77.com/posts/145067/Ha%C3%BCsa-Homes-Demonstrates-How-to-Fit-a-Folding-House-Into-a-Shipping-Container"},
        {headline:"A no-drill plywood shelf system built for renters",body:"The solution needs no screws or drilled walls, serving a generation of renters who need reversible furniture — design made for living without ownership.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/13/the-no-drill-plywood-shelf-system-every-renter-has-been-waiting-for/"},
        {headline:"Screen-free nostalgia: real toys return to cereal boxes",body:"With sales falling, big brands put physical toys back inside packaging, betting on analog affective memory as a response to digital fatigue.",source:"Fast Company",url:"https://www.fastcompany.com/91589183/screen-free-nostalgia-hits-the-cereal-aisle-with-the-return-of-real-toys"}
      ]},
      {heading:"Environment, Climate & Energy",items:[
        {headline:"Drought in Europe is shutting down nuclear reactors",body:"The lack of cooling water, worsened by the drought on the Danube and in Romania, forces plant shutdowns, exposing the climate vulnerability of an energy infrastructure considered stable.",source:"The Next Web",url:"https://thenextweb.com/news/europe-drought-nuclear-reactors-romania-danube"},
        {headline:"Backlash against data centers starts to echo anti-fossil-fuel protests",body:"Local reaction to the big computing complexes takes on the shape of classic environmental mobilization, a sign that AI infrastructure has become a matter of territorial and climate dispute.",source:"Axios",url:"https://www.axios.com/2026/08/14/data-center-backlash-fossil-fuel-protests"},
        {headline:"The largest all-electric plane ever built makes its first flight",body:"Heart Aerospace's X1 demonstrator flew for 27 minutes on about $5 of electricity, a milestone for decarbonizing regional aviation.",source:"Engadget",url:"https://www.engadget.com/2236248/the-largest-battery-electric-plane-ever-made-has-flown-for-the-first-time/"},
        {headline:"Contemporary chairs turn sustainability and stillness into design language",body:"The new collection uses responsible materials and forms of pause to propose furniture that slows you down, an example of sustainability moving from technique to experience.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/13/these-contemporary-chairs-turn-sustainability-and-stillness-into-design/"}
      ]},
      {heading:"Privacy, Surveillance & Data",items:[
        {headline:"Meta and Alibaba AI crawlers nearly destroyed a volunteer-run LGBT history archive",body:"Bots tied to big companies spiked the site's hosting costs, forcing nights of technical learning to defend itself — a portrait of scraping's invisible weight on digital memory.",source:"Fast Company",url:"https://www.fastcompany.com/91589354/ai-crawlers-hammered-a-volunteer-run-lgbt-history-archive-2"},
        {headline:"Flock tries to make it harder for cops to misuse its cameras",body:"The surveillance-camera maker adds safeguards against abuse, responding to reports that its systems feed improper searches — a case of product design pressured by accountability.",source:"Engadget",url:"https://www.engadget.com/2236415/flock-tries-to-make-its-cameras-harder-for-cops-to-misuse/"},
        {headline:"Apple sends alerts to targets of mercenary spyware",body:"The company notified users they were targeted by sophisticated espionage attacks, reigniting the debate over the commercial surveillance industry and the security of exposed individuals.",source:"Engadget",url:"https://www.engadget.com/2236825/apple-warnings-mercenary-spyware-attacks/"}
      ]},
      {heading:"Sociocultural & Behavior",items:[
        {headline:"The 'majority-minority' shift is transforming rural America",body:"Data show Black and Latino populations reshaping the US interior, a long-term demographic change with implications for politics, consumption and regional identity.",source:"Axios",url:"https://www.axios.com/2026/08/14/majority-minority-rural-america-black-latino"},
        {headline:"Save the Children's animated short uses kids'-cartoon language to talk about holiday poverty",body:"The piece, illustrated by Alice Bowsher, addresses child hunger during school breaks with a playful aesthetic, an example of design and animation in service of a sensitive social cause.",source:"It's Nice That",url:"https://www.itsnicethat.com/articles/alice-bowsher-plastic-horse-save-the-children-the-elephant-in-the-room-animation-project-130826"},
        {headline:"Meta donates 15,000 AI glasses to blind and low-vision people in Ireland",body:"The partnership with a visual-impairment charity puts AI wearables in service of accessibility, a positive counterpoint to the privacy criticism surrounding the product.",source:"Engadget",url:"https://www.engadget.com/2236054/meta-donates-15000-ray-ban-meta-glasses-to-vision-ireland/"}
      ]}
    ]
  },

  {
    id:"2026-08-13", date:"2026-08-13", displayDate:"08/13/2026",
    weekday:"Thursday", tag:"THURSDAY", edition:"08/13/2026",
    intro:"Threads for the day: AI's debate shifting from capability to responsibility — from proposals to hold firms liable for autonomous agents to the financial weight of infrastructure — an environmental axis on home energy, hydrogen, the electric transition and biomaterials, and a sociocultural read on surveillance, digital wellbeing and generational humor.",
    sections:[
      {heading:"AI: Investment, Governance & Frontiers",items:[
        {headline:"Holding companies liable in court could be the brake on 'runaway' AI",body:"Faced with agents that act on their own, legal scholars argue the most effective control is civil liability for OpenAI, Anthropic and Meta — shifting the debate from pre-emptive regulation to punishment for harm.",source:"Axios",url:"https://www.axios.com/2026/08/13/liability-ai-courts-agents-openai-anthropic-meta"},
        {headline:"Nvidia builds a trillion-parameter open model — and it'd still be smaller than China's",body:"The move reinforces the bet on open-weight models, but the comparison exposes China's lead in scale, redrawing the geopolitics of large models.",source:"The Next Web",url:"https://thenextweb.com/news/nvidia-nemotron-3-5-lightning-nemotron-4-open-weights-china"},
        {headline:"Tencent's AI compute bill outran its cash flow — and plan B is to become a 'landlord'",body:"The Chinese giant's capex grew faster than incoming cash, and renting out data-center capacity emerges as a way out, a sign of infrastructure's growing weight on corporate balance sheets.",source:"The Next Web",url:"https://thenextweb.com/news/tencent-q2-2026-capex-176-percent-free-cash-flow-negative-ai"},
        {headline:"ChatGPT and Gemini disagree on the 'best software' in a third of categories — and ignore review sites",body:"The study shows the assistants recommend different products and skip the layer of independent reviews, reigniting the dispute over how AI shapes purchase decisions.",source:"The Next Web",url:"https://thenextweb.com/news/getintel-ai-software-index-chatgpt-gemini-disagree-review-sites"},
        {headline:"The race to build a 'virtual cell' wants to simulate biology on a computer",body:"Labs are betting on AI models that reproduce how a living cell works, promising to speed up drug discovery and biomedical research without first going through the bench.",source:"Axios",url:"https://www.axios.com/2026/08/13/virtual-cell-ai-biology"}
      ]},
      {heading:"AI & Future of Work",items:[
        {headline:"Skan AI raises $63M to watch how employees work — and build agents that copy them",body:"The startup maps the real steps of office teams to automate them, a model that promises productivity but raises questions about surveillance and the replacement of human tasks.",source:"The Next Web",url:"https://thenextweb.com/news/skan-ai-63m-series-c-workplace-observation-enterprise-agents"},
        {headline:"More than half of workers would take a pay cut for job security",body:"A new survey shows the fear of losing one's job, amplified by the automation wave, weighs more than salary for much of the workforce — a portrait of insecurity in the future of work.",source:"Fast Company",url:"https://www.fastcompany.com/91588563/more-than-half-of-workers-would-take-a-pay-cut-for-job-security"}
      ]},
      {heading:"Design, Product & Architecture",items:[
        {headline:"A $549 QWERTY phone designed to 'give you your day back'",body:"The Minimal Phone 2 bets on a physical keyboard and less distraction as a deliberate design decision against algorithmic feeds and notifications, an example of a product designed for digital wellbeing.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/12/this-549-qwerty-android-phone-was-built-to-give-you-your-day-back/"},
        {headline:"An 'almost all viewfinder', screenless camera proposes a different way to shoot",body:"The Godox C100 drops the rear display to force the photographer to compose through the viewfinder, a 'form follows function' case that questions automatisms entrenched in camera design.",source:"Core77",url:"https://www.core77.com/posts/145050/Form-Follows-Function-A-New-Camera-Type-Thats-Mostly-Viewfinder-No-Screen"},
        {headline:"Xiaomi's $45,000 luxury hybrid SUV stuns with its interior",body:"The N90 Max brings highly innovative interior solutions at an aggressive price, a sign of how the Chinese industry is advancing in accessible premium automotive design.",source:"Core77",url:"https://www.core77.com/posts/145051/Xiaomis-Shocking-45000-Luxury-Hybrid-SUV"},
        {headline:"Little Giant's 'forest studio' is architecture made for its own author",body:"By designing a space for itself, with no client or brief, the firm delivers a rare exercise of formal freedom integrated into the landscape — a counterpoint to the commercial logic of the craft.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/12/little-giants-forest-studio-has-no-right-to-be-this-good/"},
        {headline:"The ENSA T1 revives the cassette player as a reaction to streaming",body:"The project bets on music that 'asks something of you' — the physical gesture of handling the media — as a design response to the passive, infinite consumption of platforms.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/12/streaming-took-something-from-us-the-ensa-t1-wants-it-back/"}
      ]},
      {heading:"Environment, Climate & Energy",items:[
        {headline:"A startup wants to turn your water heater into a 'smart thermal battery'",body:"Reservoir's ultra-efficient heater turns on when electricity is cheap, helping cut the bill and make better use of renewable energy — an example of home electrification serving the grid.",source:"Fast Company",url:"https://www.fastcompany.com/91588110/this-startup-wants-to-turn-your-water-heater-into-a-smart-thermal-battery"},
        {headline:"JCB Hydromax sets a hydrogen land-speed record: 406.320 mph",body:"Hydrogen engines built for construction machinery were taken into record-car territory, a milestone that reinforces the fuel as a low-carbon alternative for heavy applications.",source:"Yanko Design",url:"https://www.yankodesign.com/2026/08/12/jcb-hydromax-sets-a-new-hydrogen-land-speed-record-at-406-320-mph/"},
        {headline:"EVs hit a record share in China — but sales fell",body:"The paradox shows a market electrifying in proportion even as it shrinks in volume, revealing the tensions of the energy transition amid slowing consumption.",source:"The Next Web",url:"https://thenextweb.com/news/china-july-2026-car-sales-nev-share-geely-tesla-byd"},
        {headline:"A studio spent ten years perfecting a lamp made from bacteria",body:"The Cenit system's shades are grown from bacteria fed with fruit agro-industrial waste, a biomaterial case pointing to circular-economy paths in lighting design.",source:"Fast Company",url:"https://www.fastcompany.com/91586240/natural-urbano-biolamp-shade"}
      ]},
      {heading:"Privacy, Surveillance & Networks",items:[
        {headline:"German NGO files a criminal complaint over Meta's smart-glasses privacy",body:"The action argues the glasses' discreet image capture breaks the law, raising legal pressure on camera-equipped wearables and signaling tightening regulation in Europe.",source:"Engadget",url:"https://www.engadget.com/2235857/german-nonprofit-files-criminal-complaint-over-meta-smart-glasses-privacy/"},
        {headline:"Computer-generated clothing patterns promise to 'blind' AI surveillance cameras",body:"NoRecognition, created by a former intelligence chief, bets on universal adversarial camouflage against automated recognition — fashion design as a counter-surveillance tool.",source:"Fast Company",url:"https://www.fastcompany.com/91587781/norecognition-computer-generated-clothing-patterns-are-surveillance-proof"},
        {headline:"Meta faces 29 states in the biggest trial on social media and youth, with $1.4 trillion at stake",body:"The suit accuses the company of designing addictive products for teens, and the exposed figure signals the size of the legal risk tied to platform design.",source:"The Next Web",url:"https://thenextweb.com/news/meta-29-states-youth-social-media-trial"},
        {headline:"Twitch streamers can now refuse Amazon's AI training on their content",body:"The platform created an opt-out button for something critics say should have been opt-in from the start — an episode that exposes the debate over consent in using data to train models.",source:"Engadget",url:"https://www.engadget.com/2235647/twitch-streamers-can-now-refuse-to-let-amazon-train-its-gen-ai-models-on-their-content/"}
      ]},
      {heading:"Sociocultural & Behavior",items:[
        {headline:"A youth survey gives a 'thumbs down' to almost everything",body:"The survey points to broad dissatisfaction among the new generation with institutions, leaders and the country's direction, a sign of discouragement that cuts across politics, the economy and everyday life.",source:"Axios",url:"https://www.axios.com/2026/08/13/youth-poll-thumbs-down-on-everything"},
        {headline:"'Good Screens' report explores how tech could serve us better",body:"The study maps the growing appetite for devices that do good — balanced and meaningful — instead of 'bad screen time', and discusses how brands can respond creatively.",source:"It's Nice That",url:"https://www.itsnicethat.com/features/good-screens-report-its-nice-that-insights-120826"},
        {headline:"New York Fed data shows the 'K-shaped' economy isn't over",body:"The report indicates the gap between those who thrive and those who fall into debt remains open, contradicting official statements and portraying consumption strained by debt and cost of living.",source:"Fast Company",url:"https://www.fastcompany.com/91588595/k-shaped-economy-new-york-federal-reserve-treasury-secretary-scott-bessent"},
        {headline:"DeepMind's new model lets Pixel phones transcribe sign language into text",body:"The feature runs on-device and converts signs into text, an advance in AI applied to accessibility that brings technology closer to including deaf people.",source:"Engadget",url:"https://www.engadget.com/2234618/deepmind-newest-model-allows-pixel-11-devices-to-transcribe-sign-language-into-text/"}
      ]}
    ]
  }
];
